config/routes.rb
Railstest::Application.routes.draw do
  root :to => "users#index"

  resources :users do
    resources :domains
    resources :hostings
  end

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  attr_accessible :billed_price, :expiry_date, :name, :real_price, :renewal_date, :user_id

  belongs_to :user
end

app/models/hosting.rb
class Hosting < ActiveRecord::Base
  attr_accessible :expiry_date, :name, :renewal_date, :user_id, :billed_price

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :nick

  has_many :domains
  has_many :hostings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @domains }
    end
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    @domain = Domain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/new
  # GET /domains/new.json
  def new
    @domain = Domain.new
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/1/edit
  def edit
    @domain = Domain.find(params[:id])
    @user = User.find(params[:user_id])
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(params[:domain])
    # @user = User.find(params[:user_id])
    respond_to do |format|
      if @domain.save
        format.html { redirect_to users_path, notice: 'Domain was successfully created.' }
        format.json { render json: @domain, status: :created, location: @domain }
      else
        format.html { render action: "new" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /domains/1
  # PUT /domains/1.json
  def update
    @domain = Domain.find(params[:id])

    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        format.html { redirect_to users_path, notice: 'Domain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy

    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Domain was successfully removed.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/hostings_controller.rb
class HostingsController < ApplicationController
  # GET /hostings
  # GET /hostings.json
  def index
    @hostings = Hosting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hostings }
    end
  end

  # GET /hostings/1
  # GET /hostings/1.json
  def show
    @hosting = Hosting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hosting }
    end
  end

  # GET /hostings/new
  # GET /hostings/new.json
  def new
    @hosting = Hosting.new
        @user = User.find(params[:user_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hosting }
    end
  end

  # GET /hostings/1/edit
  def edit
    @hosting = Hosting.find(params[:id])
    @user = User.find(params[:user_id])
  end

  # POST /hostings
  # POST /hostings.json
  def create
    @hosting = Hosting.new(params[:hosting])


    respond_to do |format|
      if @hosting.save
        format.html { redirect_to users_path, notice: 'Hosting was successfully created.' }
        format.json { render json: @hosting, status: :created, location: @hosting }
      else
        format.html { render action: "new" }
        format.json { render json: @hosting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hostings/1
  # PUT /hostings/1.json
  def update
    @hosting = Hosting.find(params[:id])

    respond_to do |format|
      if @hosting.update_attributes(params[:hosting])
        format.html { redirect_to users_path, notice: 'Hosting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hosting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hostings/1
  # DELETE /hostings/1.json
  def destroy
    @hosting = Hosting.find(params[:id])
    @hosting.destroy

    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Hosting was successfully removed.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    sleep 0.3
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    sleep 0.3
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/hostings_helper.rb
module HostingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/domains/_form.html.erb
<%= simple_form_for [@user,@domain], :html => {:class => "form-horizontal"} do |f| %>
  <%= f.hidden_field :user_id, :value => params[:user_id] %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.input :name  %>  
  <%= f.input :renewal_date  %>  
  <%= f.input :expiry_date  %>
  <%= f.input :real_price  %>
  <%= f.input :billed_price  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<div class="container">
	<h1>Editing domain</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Back', users_path %>
</div>

app/views/domains/index.html.erb
<h1>Listing domains</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @domains.each do |domain| %>
  <tr>
    <td><%= link_to 'Show', user_domains %></td>
    <td><%= link_to 'Edit', edit_user_domain_path(domain) %></td>
    <td><%= link_to 'Destroy', user_domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Domain', new_user_domain_path %>

app/views/domains/new.html.erb
<div class="container">
	<h1>New domain</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Back', users_path %>
</div>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_domain_path(@domain) %> |
<%= link_to 'Back', user_domains_path %>

app/views/hostings/_form.html.erb
<%= simple_form_for [@user,@hosting], :html => {:class => "form-horizontal"} do |f| %>
  <%= f.hidden_field :user_id, :value => params[:user_id] %>
  <% if @hosting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hosting.errors.count, "error") %> prohibited this hosting from being saved:</h2>

      <ul>
      <% @hosting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.input :name  %>  
  <%= f.input :renewal_date  %>  
  <%= f.input :expiry_date  %>
  <%= f.input :billed_price  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hostings/edit.html.erb
<div class="container">
	<h1>Editing hosting</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Back', users_path %>
</div>

app/views/hostings/index.html.erb
<h1>Listing hostings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hostings.each do |hosting| %>
  <tr>
    <td><%= link_to 'Show', hosting %></td>
    <td><%= link_to 'Edit', edit_hosting_path(hosting) %></td>
    <td><%= link_to 'Destroy', hosting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hosting', new_hosting_path %>

app/views/hostings/new.html.erb
<div class="container">
	<h1>New hosting</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Back', users_path %>
</div>

app/views/hostings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_hosting_path(@hosting) %> |
<%= link_to 'Back', hostings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Railstest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="content">
	<%= yield %>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => {:class => "form-horizontal" } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.input :name  %>  
  <%= f.input :email  %>  
  <%= f.input :nick  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<h1>Editing user</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Listing users</h1>
    <% if flash[:notice] %>  
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% end %>
  <table class="table table-condensed table-hover">
    <colgroup>
      <col width="25%">
      <col width="25%">
      <col width="40%">
      <col width="10%">
    </colgroup>
    <thead>
      <th>asd</th>
      <th>fsa</th>
      <th>fsa</th>
      <th</th>
    </thead>

    <% @users.each do |user| %>
    <tr class="user_info">
      <td>
        <strong><%= user.name %></strong><br>
        <small><%= user.email %></small><br>
        <small><%= user.nick %></small>
      </td>
      <td>
        <%= link_to 'Edit', edit_user_path(user), :class => "btn btn-small"  %>
        <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger"  %>
      </td>
      <td>
        <%= link_to 'Dodaj domenę', new_user_domain_path(user), :class => "btn"  %>
        <%= link_to 'Dodaj hosting', new_user_hosting_path(user), :class => "btn" %>
      </td>
      <td>
        <button class="show_services btn btn-info">Usługi</button>
      </td>
    </tr>
    <tr class="services">
      <td colspan="2">
        <table class="domains table table-condensed table-bordered">
          <caption>Domeny</caption>
          <thead>
            <th>Name</th>
            <th>Renewed</th>
            <th>Expiring</th>
            <th>Real price</th>
            <th>Billed price</th>
          </thead>
          <% user.domains.each do |domain| %>
          <% if (domain.expiry_date - Date.current).to_i < 0 %>
            <tr class="alert alert-error">
          <% elsif (domain.expiry_date - Date.current).to_i < 14 %>
            <tr class="alert alert-warning">
          <% else %>
            <tr>
          <% end %>
            <td><%= domain.name %></td>
            <td><%= domain.renewal_date %></td>
            <td><%= domain.expiry_date %></td>
            <td><%= number_to_currency(domain.real_price, :locale => :pl, :unit => "PLN", :format => "%n %u"  ) %></td>
            <td><%= number_to_currency(domain.billed_price, :locale => :pl, :unit => "PLN", :format => "%n %u"  ) %></td>
            <td><%= link_to raw("<i class='icon-edit'></i>"), edit_user_domain_path(user,domain), :class => "btn btn-mini" %>&nbsp;<%= link_to raw("<i class='icon-trash icon-white'></i>"), user_domain_path(domain.user_id,domain), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger"  %></td>

          </tr>
          <% end %>
        </table>
      </td>
      <td colspan="2">
        <table class="hostings table table-condensed table-bordered">
          <caption>Hosting</caption>
          <thead>
            <th>Name</th>
            <th>Renewed</th>
            <th>Expiring</th>
            <th>Billed price</th>
          </thead>
          <% user.hostings.each do |hosting| %>
          <% if (hosting.expiry_date - Date.current).to_i < 0 %>
            <tr class="alert alert-error">
          <% elsif (hosting.expiry_date - Date.current).to_i < 14 %>
            <tr class="alert alert-warning">
          <% else %>
            <tr>
          <% end %>
            <td><%= hosting.name %></td>
            <td><%= hosting.renewal_date %></td>
            <td><%= hosting.expiry_date %></td>
            <td><%= number_to_currency(hosting.billed_price, :locale => :pl, :unit => "PLN", :format => "%n %u"  ) %></td>
            <td><%= link_to raw("<i class='icon-edit'></i>"), edit_user_hosting_path(user,hosting), :class => "btn btn-mini" %>&nbsp;<%= link_to raw("<i class='icon-trash icon-white'></i>"), user_hosting_path(hosting.user_id,hosting), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger"  %></td>
          </tr>
          <% end %>
        </table>
      </td>
    </tr>
    <% end %>
  </table>

  <br />

  <%= link_to 'New User', new_user_path, :class => "btn btn-warning" %>
</div>

app/views/users/new.html.erb
<div class="container">
	<h1>New user</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>